### ISSUE TITLE
这个是手柄在哪里的配置？

### ISSUE THREAD

**Issue by wyk111wyk** [lianglanzheng/X-Plane-11-Configuration-File-for-Xbox-Elite-Wireless-Controller-Series-2#1]
在研究mac里怎么使用手柄不小心搜到的~

**Comment by lianglanzheng** [comment]
你好，这个是 X-Plane 11 模拟飞行软件的手柄配置文件，它适配的是 Xbox Elite 无线控制器系列 2 手柄，你可以把文件复制到该软件的`Resources/joystick configs/`目录下使用。另外，该配置文件已被 Laminar Research 采纳，如果你更新 X-Plane 11 或下载其最新版本，软件内将包含本项目文件或它的改进版本。关于 X-Plane 11 手柄配置文件的更多信息请参考：[Joystick Configuration (.joy) File Specification](https://developer.x-plane.com/article/creating-joystick-configuration-joy-files/)。
如果你不使用 X-Plane 11，这个配置文件可能对你没有帮助。许多游戏手柄并不兼容 macOS，请确保你的手柄被系统正确识别。如果你的手柄不兼容 macOS，可以尝试 Xone-OSX、360Controller 等第三方驱动。
